 export const content = {
    en: {
      downloadApp: 'Download Our Mobile App',
      getOnGooglePlay: 'GET IT ON Google Play',
      downloadOnAppStore: 'Download on the App Store',
      company: 'Company',
      career: 'Career / Recruitment',
      joinTeacher: 'Join as a Teacher',
      joinAffiliate: 'Join as an Affiliate',
      privacy: 'Privacy policy',
      refund: 'Refund policy',
      terms: 'Terms & Conditions',
      others: 'Others',
      blog: 'Blog',
      bookStore: 'Book Store',
      freeNotes: 'Free Notes & Guides',
      jobCourses: 'Job Preparation Courses',
      verifyCert: 'Verify Certificate',
      freeDownload: 'Free Download',
      contact: 'Keep up with us at',
      callUs: 'Call Us: 16910 (24×7)',
      whatsapp: 'WhatsApp: +8801896016252 (24×7)',
      outsideBD: 'Outside Bangladesh: +880 9610916910',
      email: 'Email Us: support@10minuteschool.com',
      copyright: '2015 - 2025 Copyright © 10 Minute School. All rights reserved.'
    },
    bn: {
      downloadApp: 'আমাদের মোবাইল অ্যাপ ডাউনলোড করুন',
      getOnGooglePlay: 'গুগল প্লে থেকে ডাউনলোড করুন',
      downloadOnAppStore: 'অ্যাপ স্টোর থেকে ডাউনলোড করুন',
      company: 'কোম্পানি',
      career: 'ক্যারিয়ার / নিয়োগ',
      joinTeacher: 'শিক্ষক হিসেবে যোগ দিন',
      joinAffiliate: 'অ্যাফিলিয়েট হিসেবে যোগ দিন',
      privacy: 'গোপনীয়তা নীতি',
      refund: 'ফেরত নীতি',
      terms: 'শর্তাবলী',
      others: 'অন্যান্য',
      blog: 'ব্লগ',
      bookStore: 'বইয়ের দোকান',
      freeNotes: 'ফ্রি নোট ও গাইড',
      jobCourses: 'চাকরি প্রস্তুতি কোর্স',
      verifyCert: 'সার্টিফিকেট যাচাই করুন',
      freeDownload: 'ফ্রি ডাউনলোড',
      contact: 'আমাদের সাথে যোগাযোগ করুন',
      callUs: 'কল করুন: ১৬৯১০ (২৪×৭)',
      whatsapp: 'হোয়াটসঅ্যাপ: +৮৮০১৮৯৬০১৬২৫২ (২৪×৭)',
      outsideBD: 'বাংলাদেশের বাইরে: +৮৮০ ৯৬১০৯১৬৯১০',
      email: 'ইমেইল: support@10minuteschool.com',
      copyright: '২০১৫ - ২০২৫ কপিরাইট © ১০ মিনিট স্কুল। সর্বস্বত্ব সংরক্ষিত।'
    }
  };